name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo clippy
        run: |
          cargo clippy --all-features --all-targets --workspace -- -D warnings
      - name: cargo test
        run: |
          cargo test --workspace
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install & Build
        run: |
          npm install
          npm run release-build
          rm ./public/pkg/.gitignore
          ls -R
